/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package anagrafescolasticagorettibucci;

/**
 *
 * @author goretti.leonardo
 */
public class AnagrafeGUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AnagrafeGUI.class.getName());

    /**
     * Creates new form AnagrafeGUI
     */
    public AnagrafeGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        IscrizioneStudente = new javax.swing.JPanel();
        LBLNome = new javax.swing.JLabel();
        LBLCognome = new javax.swing.JLabel();
        LBLMatricola = new javax.swing.JLabel();
        TXTNome = new javax.swing.JTextField();
        TXTCognome = new javax.swing.JTextField();
        TXTMatricola = new javax.swing.JTextField();
        Titolo = new javax.swing.JPanel();
        LBLTitolo = new javax.swing.JLabel();
        PannelloBottoni = new javax.swing.JPanel();
        BTNConferma = new javax.swing.JButton();
        BTNElimina = new javax.swing.JButton();
        BTNCrea = new javax.swing.JButton();
        BTNCarica = new javax.swing.JButton();
        BTNSalva = new javax.swing.JButton();
        DisplayAnagrafe = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TBLAnagrafe = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Anagrafe Scolastica");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        IscrizioneStudente.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        LBLNome.setText("Nome:");

        LBLCognome.setText("Cognome:");

        LBLMatricola.setText("Matricola:");

        javax.swing.GroupLayout IscrizioneStudenteLayout = new javax.swing.GroupLayout(IscrizioneStudente);
        IscrizioneStudente.setLayout(IscrizioneStudenteLayout);
        IscrizioneStudenteLayout.setHorizontalGroup(
            IscrizioneStudenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IscrizioneStudenteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(IscrizioneStudenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(IscrizioneStudenteLayout.createSequentialGroup()
                        .addComponent(LBLNome, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(TXTNome, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE))
                    .addGroup(IscrizioneStudenteLayout.createSequentialGroup()
                        .addComponent(LBLMatricola)
                        .addGap(47, 47, 47)
                        .addComponent(TXTMatricola))
                    .addGroup(IscrizioneStudenteLayout.createSequentialGroup()
                        .addComponent(LBLCognome)
                        .addGap(44, 44, 44)
                        .addComponent(TXTCognome)))
                .addContainerGap())
        );
        IscrizioneStudenteLayout.setVerticalGroup(
            IscrizioneStudenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, IscrizioneStudenteLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(IscrizioneStudenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LBLNome)
                    .addComponent(TXTNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(IscrizioneStudenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LBLCognome)
                    .addComponent(TXTCognome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(IscrizioneStudenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LBLMatricola)
                    .addComponent(TXTMatricola, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );

        getContentPane().add(IscrizioneStudente, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 200, 180));

        Titolo.setBackground(new java.awt.Color(51, 255, 0));
        Titolo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        LBLTitolo.setFont(new java.awt.Font("Sylfaen", 0, 24)); // NOI18N
        LBLTitolo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LBLTitolo.setText("Anagrafe scolastica");

        javax.swing.GroupLayout TitoloLayout = new javax.swing.GroupLayout(Titolo);
        Titolo.setLayout(TitoloLayout);
        TitoloLayout.setHorizontalGroup(
            TitoloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TitoloLayout.createSequentialGroup()
                .addComponent(LBLTitolo, javax.swing.GroupLayout.DEFAULT_SIZE, 1040, Short.MAX_VALUE)
                .addContainerGap())
        );
        TitoloLayout.setVerticalGroup(
            TitoloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TitoloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LBLTitolo, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(Titolo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 60));

        PannelloBottoni.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        BTNConferma.setText("Conferma studente");

        BTNElimina.setText("Elimina studente");

        BTNCrea.setText("Cerca studente");

        BTNCarica.setText("Carica file");

        BTNSalva.setText("Salva file");

        javax.swing.GroupLayout PannelloBottoniLayout = new javax.swing.GroupLayout(PannelloBottoni);
        PannelloBottoni.setLayout(PannelloBottoniLayout);
        PannelloBottoniLayout.setHorizontalGroup(
            PannelloBottoniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PannelloBottoniLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(BTNConferma)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addComponent(BTNElimina)
                .addGap(73, 73, 73)
                .addComponent(BTNCrea)
                .addGap(189, 189, 189)
                .addComponent(BTNCarica)
                .addGap(18, 18, 18)
                .addComponent(BTNSalva)
                .addGap(75, 75, 75))
        );
        PannelloBottoniLayout.setVerticalGroup(
            PannelloBottoniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PannelloBottoniLayout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addGroup(PannelloBottoniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTNConferma)
                    .addComponent(BTNElimina)
                    .addComponent(BTNCrea)
                    .addComponent(BTNCarica)
                    .addComponent(BTNSalva))
                .addGap(35, 35, 35))
        );

        getContentPane().add(PannelloBottoni, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 1020, -1));

        DisplayAnagrafe.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        TBLAnagrafe.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Matricola", "Nome", "Cognome"
            }
        ));
        jScrollPane2.setViewportView(TBLAnagrafe);

        javax.swing.GroupLayout DisplayAnagrafeLayout = new javax.swing.GroupLayout(DisplayAnagrafe);
        DisplayAnagrafe.setLayout(DisplayAnagrafeLayout);
        DisplayAnagrafeLayout.setHorizontalGroup(
            DisplayAnagrafeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DisplayAnagrafeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 774, Short.MAX_VALUE)
                .addContainerGap())
        );
        DisplayAnagrafeLayout.setVerticalGroup(
            DisplayAnagrafeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DisplayAnagrafeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(DisplayAnagrafe, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, 790, 180));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AnagrafeGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNCarica;
    private javax.swing.JButton BTNConferma;
    private javax.swing.JButton BTNCrea;
    private javax.swing.JButton BTNElimina;
    private javax.swing.JButton BTNSalva;
    private javax.swing.JPanel DisplayAnagrafe;
    private javax.swing.JPanel IscrizioneStudente;
    private javax.swing.JLabel LBLCognome;
    private javax.swing.JLabel LBLMatricola;
    private javax.swing.JLabel LBLNome;
    private javax.swing.JLabel LBLTitolo;
    private javax.swing.JPanel PannelloBottoni;
    private javax.swing.JTable TBLAnagrafe;
    private javax.swing.JTextField TXTCognome;
    private javax.swing.JTextField TXTMatricola;
    private javax.swing.JTextField TXTNome;
    private javax.swing.JPanel Titolo;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
