/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package anagrafescolasticagorettibucci;

import java.util.ArrayList;

/**
 *
 * @author goretti.leonardo
 */
public class AnagrafeGUI extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AnagrafeGUI.class.getName());

    /**
     * Crea il form
     */
    public AnagrafeGUI() {
        initComponents();
        anagrafe = new Anagrafe();
        file = new GestioneFile();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        IscrizioneStudente = new javax.swing.JPanel();
        LBLNome = new javax.swing.JLabel();
        LBLCognome = new javax.swing.JLabel();
        LBLMatricola = new javax.swing.JLabel();
        TXTNome = new javax.swing.JTextField();
        TXTCognome = new javax.swing.JTextField();
        TXTMatricola = new javax.swing.JTextField();
        Titolo = new javax.swing.JPanel();
        LBLTitolo = new javax.swing.JLabel();
        PannelloBottoni = new javax.swing.JPanel();
        BTNConferma = new javax.swing.JButton();
        BTNElimina = new javax.swing.JButton();
        BTNCrea = new javax.swing.JButton();
        BTNCarica = new javax.swing.JButton();
        BTNSalva = new javax.swing.JButton();
        DisplayAnagrafe = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TBLAnagrafe = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Anagrafe Scolastica");
        setMinimumSize(new java.awt.Dimension(1046, 445));
        setPreferredSize(new java.awt.Dimension(1046, 445));
        setResizable(false);
        setSize(new java.awt.Dimension(1046, 445));
        getContentPane().setLayout(null);

        IscrizioneStudente.setLayout(null);

        LBLNome.setText("Nome:");
        IscrizioneStudente.add(LBLNome);
        LBLNome.setBounds(8, 30, 60, 16);

        LBLCognome.setText("Cognome:");
        IscrizioneStudente.add(LBLCognome);
        LBLCognome.setBounds(8, 86, 80, 16);

        LBLMatricola.setText("Matricola:");
        IscrizioneStudente.add(LBLMatricola);
        LBLMatricola.setBounds(8, 142, 80, 16);
        IscrizioneStudente.add(TXTNome);
        TXTNome.setBounds(108, 30, 84, 22);
        IscrizioneStudente.add(TXTCognome);
        TXTCognome.setBounds(108, 86, 84, 22);
        IscrizioneStudente.add(TXTMatricola);
        TXTMatricola.setBounds(108, 142, 84, 22);

        getContentPane().add(IscrizioneStudente);
        IscrizioneStudente.setBounds(20, 90, 200, 180);

        Titolo.setBackground(new java.awt.Color(51, 255, 0));
        Titolo.setLayout(null);

        LBLTitolo.setFont(new java.awt.Font("Sylfaen", 0, 24)); // NOI18N
        LBLTitolo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LBLTitolo.setText("Anagrafe scolastica");
        Titolo.add(LBLTitolo);
        LBLTitolo.setBounds(2, 8, 1040, 44);

        getContentPane().add(Titolo);
        Titolo.setBounds(0, 0, 1050, 60);

        PannelloBottoni.setLayout(null);

        BTNConferma.setText("Conferma studente");
        BTNConferma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNConfermaActionPerformed(evt);
            }
        });
        PannelloBottoni.add(BTNConferma);
        BTNConferma.setBounds(49, 40, 180, 23);

        BTNElimina.setText("Elimina studente");
        BTNElimina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNEliminaActionPerformed(evt);
            }
        });
        PannelloBottoni.add(BTNElimina);
        BTNElimina.setBounds(278, 40, 160, 23);

        BTNCrea.setText("Cerca studente");
        BTNCrea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNCreaActionPerformed(evt);
            }
        });
        PannelloBottoni.add(BTNCrea);
        BTNCrea.setBounds(469, 40, 170, 23);

        BTNCarica.setText("Carica file");
        BTNCarica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNCaricaActionPerformed(evt);
            }
        });
        PannelloBottoni.add(BTNCarica);
        BTNCarica.setBounds(860, 20, 110, 23);

        BTNSalva.setText("Salva file");
        BTNSalva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNSalvaActionPerformed(evt);
            }
        });
        PannelloBottoni.add(BTNSalva);
        BTNSalva.setBounds(860, 60, 110, 23);

        getContentPane().add(PannelloBottoni);
        PannelloBottoni.setBounds(20, 290, 1020, 100);

        DisplayAnagrafe.setLayout(null);

        TBLAnagrafe.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Matricola", "Nome", "Cognome"
            }
        ));
        TBLAnagrafe.setEnabled(false);
        jScrollPane2.setViewportView(TBLAnagrafe);

        DisplayAnagrafe.add(jScrollPane2);
        jScrollPane2.setBounds(8, 8, 774, 166);

        getContentPane().add(DisplayAnagrafe);
        DisplayAnagrafe.setBounds(250, 90, 790, 180);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Aggiorna la tabella con i dati degli studenti quando per esempio vengono aggiunti
     */
    private void aggiornaTabella() {
        javax.swing.table.DefaultTableModel model
                = (javax.swing.table.DefaultTableModel) TBLAnagrafe.getModel();
        model.setRowCount(0); // svuota la tabella
        for (Studente s : anagrafe.getTuttiStudenti()) {
            model.addRow(new Object[]{s.getMatricola(), s.getNome(), s.getCognome()});
        }
    }


    /**
     * Serve ad inviare i dati dello studente
     * @param evt 
     */
    private void BTNConfermaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNConfermaActionPerformed
        String nome = TXTNome.getText().trim();
        String cognome = TXTCognome.getText().trim();
        String matricola = TXTMatricola.getText().trim();

        if (nome.isEmpty() || cognome.isEmpty() || matricola.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Compila tutti i campi!");
            return;
        }

        Studente s = new Studente(nome, cognome, matricola);
        if (anagrafe.aggiungiStudente(s)) {
            aggiornaTabella();
            TXTNome.setText("");
            TXTCognome.setText("");
            TXTMatricola.setText("");
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Matricola già esistente!");
        }
    }//GEN-LAST:event_BTNConfermaActionPerformed

    /**
     * Elimina uno studente in base alla matricola
     * @param evt 
     */
    private void BTNEliminaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNEliminaActionPerformed
        if (anagrafe.eliminaStudente(TXTMatricola.getText())) {
            aggiornaTabella();

        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "lo studente selezionato non esiste");
        }


    }//GEN-LAST:event_BTNEliminaActionPerformed

    /**
     * Cerca lo studente in base alla matricola "ho sbgliato a scrivere il nome del bottone volevo dire Cerca"
     * @param evt 
     */
    private void BTNCreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNCreaActionPerformed
        try {
            TXTNome.setText(anagrafe.cercaStudente(TXTMatricola.getText()).getNome());
            TXTCognome.setText(anagrafe.cercaStudente(TXTMatricola.getText()).getCognome());
        } catch (java.lang.NullPointerException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "lo studente che vuoi cercare non esiste");
        }

    }//GEN-LAST:event_BTNCreaActionPerformed

    /**
     * Salva la lista degli studenti nel file anagrafe.txt
     * @param evt 
     */
    private void BTNSalvaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNSalvaActionPerformed

        file.salvaSuFile("anagrafe.txt", anagrafe.getTuttiStudenti());
    }//GEN-LAST:event_BTNSalvaActionPerformed

    /**
     * Carica la tabella dal file
     * @param evt 
     */
    private void BTNCaricaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNCaricaActionPerformed
        ArrayList<Studente> lista = file.caricaDaFile("anagrafe.txt");
        for (Studente s : lista) {
            anagrafe.aggiungiStudente(s);  
        }
        aggiornaTabella();
    }//GEN-LAST:event_BTNCaricaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AnagrafeGUI().setVisible(true));
    }

    private Anagrafe anagrafe;
    private GestioneFile file;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNCarica;
    private javax.swing.JButton BTNConferma;
    private javax.swing.JButton BTNCrea;
    private javax.swing.JButton BTNElimina;
    private javax.swing.JButton BTNSalva;
    private javax.swing.JPanel DisplayAnagrafe;
    private javax.swing.JPanel IscrizioneStudente;
    private javax.swing.JLabel LBLCognome;
    private javax.swing.JLabel LBLMatricola;
    private javax.swing.JLabel LBLNome;
    private javax.swing.JLabel LBLTitolo;
    private javax.swing.JPanel PannelloBottoni;
    private javax.swing.JTable TBLAnagrafe;
    private javax.swing.JTextField TXTCognome;
    private javax.swing.JTextField TXTMatricola;
    private javax.swing.JTextField TXTNome;
    private javax.swing.JPanel Titolo;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
